### ISSUE TITLE
限时优惠，健康饮品等四个板块点击更多，顶部不应该显示英文

### ISSUE THREAD

**Issue by zengfanzgai** [wanliu/LeiyangStreet#45]
![20](https://cloud.githubusercontent.com/assets/6811363/13896455/9cc72940-edc6-11e5-8600-c974ff48369f.png)

**Comment by satbirdd** [comment]
working on it

**Comment by wuzhidexiaoheizi** [comment]
已修复

**Comment by zengfanzgai** [comment]
1
