### ISSUE TITLE
健康饮品下的商品点击查看页面拉不到最底部

### ISSUE THREAD

**Issue by zengfanzgai** [wanliu/LeiyangStreet#81]
![Uploading 32.png…]()

**Comment by zengfanzgai** [comment]
![32](https://cloud.githubusercontent.com/assets/6811363/14009381/56ede176-f1c6-11e5-8bfb-1fa81c677ad6.png)

**Comment by momentmj** [comment]
已修复

**Comment by zengfanzgai** [comment]
1
