### ISSUE TITLE
热卖商品下的问题要修改

### ISSUE THREAD

**Issue by zengfanzgai** [wanliu/LeiyangStreet#92]
1.商品名称要控制只显示两行
![34](https://cloud.githubusercontent.com/assets/6811363/14071581/fc5a78ca-f4e8-11e5-9300-c2ec7a94ebc9.png)

2.如果没有加载商品了，不能显示“继续加载”，文字修改一下
![35](https://cloud.githubusercontent.com/assets/6811363/14071629/7c7121e4-f4e9-11e5-97a7-5f869e87ecbb.png)

**Comment by wuzhidexiaoheizi** [comment]
已修复

**Comment by zengfanzgai** [comment]
1
